trigger cd pipeline with azure api

diff --git a/ops/ci.yaml b/ops/ci.yaml
--- a/ops/ci.yaml
+++ b/ops/ci.yaml
@@ -17,6 +17,7 @@ variables:
   Docker.url: "uniappsakshopedev.azurecr.io"
   tag: $(Build.SourceVersion)
   additionalTag: $(Build.SourceBranchName)
+  pipelineId: 1143
 
 
 stages:
@@ -98,13 +99,37 @@ stages:
               --push \
               ./
             displayName: Docker build prd
+
+  - stage: trigger_deploy
+    displayName: Trigger deploy
+    dependsOn: [build_and_push_prd]
+    jobs:
+      - job: trigger_deploy
+        pool:
+          vmImage: ubuntu-latest
+        displayName: "[TRIGGER_DEPLOY]"
+        steps:
           - script: |
-              mkdir -p $(Build.ArtifactStagingDirectory)/tag
-              echo $(tag) > $(Build.ArtifactStagingDirectory)/tag/hpg.txt
-            displayName: "Save tag to file"
-          - task: PublishPipelineArtifact@1
-            inputs:
-              pathToPublish: "$(Build.ArtifactStagingDirectory)/tag"
-              artifact: 'hope-payment-gateway'
-              publishLocation: 'pipeline'
-            displayName: "Publish tag"
+              pipelineId=$(pipelineId)
+              IFS=',' read -ra pipelines <<< "$pipelineId"
+              for pipeline in "${pipelines[@]}"; do
+                jsonBody='{"variables": {"tag": {"isSecret": false, "value": "$(tag)"}}}'
+                contentLength=$(echo -n $jsonBody | wc -c)
+                project=ICTD-HCT-MIS
+                organization=unicef
+
+                echo Triggering deploy for pipeline $pipeline
+                echo JSON body: $jsonBody
+
+                curl -v -L \
+                  -u ":$(AZURE_PAT)" \
+                  -H "Content-Type: application/json" \
+                  -H "Content-Length: $contentLength" \
+                  -d "$jsonBody" \
+                  https://dev.azure.com/$organization/$project/_apis/pipelines/$pipeline/runs?api-version=7.1-preview.1
+                if [ $? -ne 0 ]; then
+                  echo "Failed to trigger deploy for pipeline $pipeline"
+                  exit 1
+                fi
+              done
+            displayName: "Trigger deploy"
